version: '3'
services:
  frontend:
    image: pasfront:1.0.0
    # build:
    # context: ./frontend
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./frontend/:/usr/src/app
    command: npm run start

  backend:
    image: pasback:1.0.0
    # build:
    # context: ./backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/usr/src/app
    command: bash -c "yarn sequelize-cli db:migrate && yarn start:dev"
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres
    # build:
    # context: ./database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pasprogweb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata/:/var/lib/postgresql/data/
    networks:
      - db

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: anderson@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 123
  #     POSTGRES_DB: pas
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./db/pgadmin/:/var/lib/pgadmin
  #   networks:
  #     - db

networks:
  db:
