version: '3'
services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 4200:4200
    command: npm run start

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 8000:8000
    command: bash -c "npx sequelize db:migrate && npm run start"
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pasprogweb
    volumes:
      - ./db/pgdata/:/var/lib/postgresql/data/
    networks:
      - db

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: anderson@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 123
  #     POSTGRES_DB: pas
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./db/pgadmin/:/var/lib/pgadmin
  #   networks:
  #     - db

networks:
  db:
