version: '3'

services:
  frontend:
    image: pasfront:1.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend/:/usr/src/app
    command: npm run start
    networks:
      - default

  backend:
    image: pasback:1.0.0
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/usr/src/app
    command: yarn start:dev
